---
apiVersion: v2
name: script-exporter
description: Prometheus exporter to execute scripts and collect metrics from the output or the exit status.
type: application
version: 0.10.1
appVersion: v2.23.1
